import { describe, expect, it } from "vitest";
import { summarizeReleaseGateArtifact } from "./releaseGateArtifactSummary";

describe("release gate artifact summary", () => {
  it("keeps repository readiness fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        repositoryReadinessPassed: true,
        repositoryReadinessBlockerCount: 0,
        repositoryReadinessCheckCount: 4,
        repositoryReadinessPassedCheckCount: 4,
      },
    })).toMatchObject({
      repositoryReadinessPassed: true,
      repositoryReadinessBlockerCount: 0,
      repositoryReadinessCheckCount: 4,
      repositoryReadinessPassedCheckCount: 4,
    });
  });

  it("keeps v12 production archive fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        v12ProductionArchivePassed: true,
        v12ProductionSuitePassed: true,
        v12ProductionDeployBackendId: "compiled-browser-webllm",
        v12ProductionKernelLabBackendId: "unlocked-browser-transformer",
        v12ProductionFallbackBackendId: "wasm-small-core",
        v12ProductionBackendRoleBoundaryPassed: true,
        v12ProductionHostedBenchmarkProofRequired: true,
        v12ProductionHostedBenchmarkProofPassed: true,
        v12ProductionBackendReadinessProofBound: true,
        v12ProductionModelRegistryAligned: true,
        v12ProductionModelRegistryModelCount: 3,
        v12ProductionPublicModelOptionCount: 2,
        v12ProductionPublicDeployOptionCount: 1,
        v12ProductionPublicKernelLabOptionCount: 1,
        v12ProductionArtifactCount: 7,
        v12ProductionSuiteArtifactCount: 6,
        v12ProductionChildArtifactCount: 5,
        v12ProductionHostedBenchmarkRuntimeBackendId: "compiled-browser-webllm",
        v12ProductionHostedBenchmarkDeployBackendId: "compiled-browser-webllm",
        v12ProductionCompiledBackendReadyPassed: true,
        v12ProductionDeployReadyPassed: true,
        v12ProductionMemoryGroundingPassed: true,
        v12ProductionConcreteMemoryGroundingPassed: true,
        v12ProductionMemoryGroundingRunCount: 1,
        v12ProductionMemoryGroundingCaseId: "montana_capital",
        v12ProductionMemorySeededCorpusCount: 16,
        v12ProductionMemoryRetrievedCount: 1,
        v12ProductionMemoryIncludedCount: 1,
        v12ProductionMemoryExpectedMemoryIdCount: 1,
        v12ProductionMemoryExpectedHitMeanRank: 1,
        v12ProductionMemoryExpectedHitMinTopScoreMargin: 0.4,
        v12ProductionExpectedExactPassed: true,
        v12ProductionSpeedFloorPassed: true,
        v12ProductionMeanTokensPerSecond: 2.7,
        v12ProductionDirectModelFactualProofUsed: false,
        v12ProductionTechnicalProofOnly: false,
        v12ProductionCpuFallbackUsed: false,
        v12ProductionStrictWebGpuPassed: true,
        v12ProductionProofSchemaVersion: 2,
        v12ProductionProofSourceGitSha: "abc123",
        v12ProductionExpectedSourceGitSha: "abc123",
        v12ProductionProofSourceBoundRequired: true,
        v12ProductionProofSourceBound: true,
        v12ProductionBrokerDeployBackendId: "compiled-browser-webllm",
        v12ProductionBrokerKernelLabBackendId: "unlocked-browser-transformer",
        v12ProductionBrokerFallbackBackendId: "wasm-small-core",
        v12ProductionBrokerFallbackBackendCount: 1,
        v12ProductionBrokerFallbackDeployReadyCandidate: false,
        v12ProductionBrokerRoleBoundaryPassed: true,
      },
    })).toMatchObject({
      v12ProductionArchivePassed: true,
      v12ProductionSuitePassed: true,
      v12ProductionDeployBackendId: "compiled-browser-webllm",
      v12ProductionKernelLabBackendId: "unlocked-browser-transformer",
      v12ProductionFallbackBackendId: "wasm-small-core",
      v12ProductionBackendRoleBoundaryPassed: true,
      v12ProductionHostedBenchmarkProofRequired: true,
      v12ProductionHostedBenchmarkProofPassed: true,
      v12ProductionBackendReadinessProofBound: true,
      v12ProductionModelRegistryAligned: true,
      v12ProductionModelRegistryModelCount: 3,
      v12ProductionPublicModelOptionCount: 2,
      v12ProductionPublicDeployOptionCount: 1,
      v12ProductionPublicKernelLabOptionCount: 1,
      v12ProductionArtifactCount: 7,
      v12ProductionSuiteArtifactCount: 6,
      v12ProductionChildArtifactCount: 5,
      v12ProductionHostedBenchmarkRuntimeBackendId: "compiled-browser-webllm",
      v12ProductionHostedBenchmarkDeployBackendId: "compiled-browser-webllm",
      v12ProductionCompiledBackendReadyPassed: true,
      v12ProductionDeployReadyPassed: true,
      v12ProductionMemoryGroundingPassed: true,
      v12ProductionConcreteMemoryGroundingPassed: true,
      v12ProductionMemoryGroundingRunCount: 1,
      v12ProductionMemoryGroundingCaseId: "montana_capital",
      v12ProductionMemorySeededCorpusCount: 16,
      v12ProductionMemoryRetrievedCount: 1,
      v12ProductionMemoryIncludedCount: 1,
      v12ProductionMemoryExpectedMemoryIdCount: 1,
      v12ProductionMemoryExpectedHitMeanRank: 1,
      v12ProductionMemoryExpectedHitMinTopScoreMargin: 0.4,
      v12ProductionExpectedExactPassed: true,
      v12ProductionSpeedFloorPassed: true,
      v12ProductionMeanTokensPerSecond: 2.7,
      v12ProductionDirectModelFactualProofUsed: false,
      v12ProductionTechnicalProofOnly: false,
      v12ProductionCpuFallbackUsed: false,
      v12ProductionStrictWebGpuPassed: true,
      v12ProductionProofSchemaVersion: 2,
      v12ProductionProofSourceGitSha: "abc123",
      v12ProductionExpectedSourceGitSha: "abc123",
      v12ProductionProofSourceBoundRequired: true,
      v12ProductionProofSourceBound: true,
      v12ProductionBrokerDeployBackendId: "compiled-browser-webllm",
      v12ProductionBrokerKernelLabBackendId: "unlocked-browser-transformer",
      v12ProductionBrokerFallbackBackendId: "wasm-small-core",
      v12ProductionBrokerFallbackBackendCount: 1,
      v12ProductionBrokerFallbackDeployReadyCandidate: false,
      v12ProductionBrokerRoleBoundaryPassed: true,
    });
  });

  it("keeps hosted benchmark proof fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        hostedBenchmarkProofPassed: true,
        hostedBenchmarkArtifactPath: ".artifacts/evals/hosted/browser-runtime-bench-latest.json",
        hostedBenchmarkRuntimeBackendId: "compiled-browser-webllm",
        hostedBenchmarkDeployBackendId: "compiled-browser-webllm",
        hostedBenchmarkCompiledBackendReadyPassed: true,
        hostedBenchmarkProductionDeployReadyPassed: true,
        hostedBenchmarkMemoryGroundingPassed: true,
        hostedBenchmarkConcreteMemoryGroundingPassed: true,
        hostedBenchmarkMemoryGroundingRunCount: 1,
        hostedBenchmarkMemoryGroundingCaseId: "montana_capital",
        hostedBenchmarkMemorySeededCorpusCount: 16,
        hostedBenchmarkMemoryRetrievedCount: 1,
        hostedBenchmarkMemoryIncludedCount: 1,
        hostedBenchmarkMemoryExpectedMemoryIdCount: 1,
        hostedBenchmarkMemoryExpectedHitMeanRank: 1,
        hostedBenchmarkMemoryExpectedHitMinTopScoreMargin: 0.4,
        hostedBenchmarkExpectedExactPassed: true,
        hostedBenchmarkProductionSpeedFloorPassed: true,
        hostedBenchmarkMeanTokensPerSecond: 2.7,
        hostedBenchmarkDirectModelFactualProofUsed: false,
        hostedBenchmarkTechnicalProofOnly: false,
        hostedBenchmarkCpuFallbackUsed: false,
        hostedBenchmarkStrictWebGpuPassed: true,
        hostedBenchmarkV12ProductionProofSchemaVersion: 2,
        hostedBenchmarkProofSourceGitSha: "abc123",
        hostedBenchmarkProofSourceBoundRequired: true,
        hostedBenchmarkBrokerDeployBackendId: "compiled-browser-webllm",
        hostedBenchmarkBrokerKernelLabBackendId: "unlocked-browser-transformer",
        hostedBenchmarkBrokerFallbackBackendId: "wasm-small-core",
        hostedBenchmarkBrokerFallbackBackendCount: 1,
        hostedBenchmarkBrokerFallbackDeployReadyCandidate: false,
        hostedBenchmarkBrokerRoleBoundaryPassed: true,
      },
    })).toMatchObject({
      hostedBenchmarkProofPassed: true,
      hostedBenchmarkArtifactPath: ".artifacts/evals/hosted/browser-runtime-bench-latest.json",
      hostedBenchmarkRuntimeBackendId: "compiled-browser-webllm",
      hostedBenchmarkDeployBackendId: "compiled-browser-webllm",
      hostedBenchmarkCompiledBackendReadyPassed: true,
      hostedBenchmarkProductionDeployReadyPassed: true,
      hostedBenchmarkMemoryGroundingPassed: true,
      hostedBenchmarkConcreteMemoryGroundingPassed: true,
      hostedBenchmarkMemoryGroundingRunCount: 1,
      hostedBenchmarkMemoryGroundingCaseId: "montana_capital",
      hostedBenchmarkMemorySeededCorpusCount: 16,
      hostedBenchmarkMemoryRetrievedCount: 1,
      hostedBenchmarkMemoryIncludedCount: 1,
      hostedBenchmarkMemoryExpectedMemoryIdCount: 1,
      hostedBenchmarkMemoryExpectedHitMeanRank: 1,
      hostedBenchmarkMemoryExpectedHitMinTopScoreMargin: 0.4,
      hostedBenchmarkExpectedExactPassed: true,
      hostedBenchmarkProductionSpeedFloorPassed: true,
      hostedBenchmarkMeanTokensPerSecond: 2.7,
      hostedBenchmarkDirectModelFactualProofUsed: false,
      hostedBenchmarkTechnicalProofOnly: false,
      hostedBenchmarkCpuFallbackUsed: false,
      hostedBenchmarkStrictWebGpuPassed: true,
      hostedBenchmarkV12ProductionProofSchemaVersion: 2,
      hostedBenchmarkProofSourceGitSha: "abc123",
      hostedBenchmarkProofSourceBoundRequired: true,
      hostedBenchmarkBrokerDeployBackendId: "compiled-browser-webllm",
      hostedBenchmarkBrokerKernelLabBackendId: "unlocked-browser-transformer",
      hostedBenchmarkBrokerFallbackBackendId: "wasm-small-core",
      hostedBenchmarkBrokerFallbackBackendCount: 1,
      hostedBenchmarkBrokerFallbackDeployReadyCandidate: false,
      hostedBenchmarkBrokerRoleBoundaryPassed: true,
    });
  });

  it("keeps v12 readiness suite fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        v12SuitePassed: true,
        v12SuiteArtifactCount: 5,
        v12SuiteChildArtifactCount: 4,
        v12SuiteDeployBackendId: "compiled-browser-webllm",
        v12SuiteKernelLabBackendId: "unlocked-browser-transformer",
        v12SuiteFallbackBackendId: "wasm-small-core",
        v12SuiteBackendRoleBoundaryPassed: true,
        v12SuiteRequirementCount: 5,
        v12SuitePassedRequirementCount: 5,
        v12SuiteHostedProfilePassed: true,
        v12SuiteBackendReadinessPassed: true,
        v12SuiteSharedRuntimePassed: true,
        v12SuiteReadinessBundlePassed: true,
        v12SuiteHostedBenchmarkProofRequired: true,
        v12SuiteHostedBenchmarkProofSourceBoundRequired: true,
        v12SuiteHostedBenchmarkProofPassed: true,
      },
    })).toMatchObject({
      v12SuitePassed: true,
      v12SuiteArtifactCount: 5,
      v12SuiteChildArtifactCount: 4,
      v12SuiteDeployBackendId: "compiled-browser-webllm",
      v12SuiteKernelLabBackendId: "unlocked-browser-transformer",
      v12SuiteFallbackBackendId: "wasm-small-core",
      v12SuiteBackendRoleBoundaryPassed: true,
      v12SuiteRequirementCount: 5,
      v12SuitePassedRequirementCount: 5,
      v12SuiteHostedProfilePassed: true,
      v12SuiteBackendReadinessPassed: true,
      v12SuiteSharedRuntimePassed: true,
      v12SuiteReadinessBundlePassed: true,
      v12SuiteHostedBenchmarkProofRequired: true,
      v12SuiteHostedBenchmarkProofSourceBoundRequired: true,
      v12SuiteHostedBenchmarkProofPassed: true,
    });
  });

  it("keeps v12 readiness bundle fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        v12ReadinessPassed: true,
        v12DeployBackendId: "compiled-browser-webllm",
        v12KernelLabBackendId: "unlocked-browser-transformer",
        v12FallbackBackendId: "wasm-small-core",
        v12BackendRoleBoundaryPassed: true,
        v12ModelRegistryAligned: true,
        v12ModelRegistryModelCount: 3,
        v12PublicModelOptionCount: 2,
        v12PublicDeployOptionCount: 1,
        v12PublicKernelLabOptionCount: 1,
        v12RequirementCount: 6,
        v12PassedRequirementCount: 6,
        v12HostedProfilePassed: true,
        v12BackendReadinessPassed: true,
        v12SharedRuntimePassed: true,
      },
    })).toMatchObject({
      v12ReadinessPassed: true,
      v12DeployBackendId: "compiled-browser-webllm",
      v12KernelLabBackendId: "unlocked-browser-transformer",
      v12FallbackBackendId: "wasm-small-core",
      v12BackendRoleBoundaryPassed: true,
      v12ModelRegistryAligned: true,
      v12ModelRegistryModelCount: 3,
      v12PublicModelOptionCount: 2,
      v12PublicDeployOptionCount: 1,
      v12PublicKernelLabOptionCount: 1,
      v12RequirementCount: 6,
      v12PassedRequirementCount: 6,
      v12HostedProfilePassed: true,
      v12BackendReadinessPassed: true,
      v12SharedRuntimePassed: true,
    });
  });

  it("keeps shared runtime readiness fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        sharedRuntimeReadinessPassed: true,
        sharedRuntimeCoveredBackendCount: 3,
        sharedRuntimeDeployBackendId: "compiled-browser-webllm",
        sharedRuntimeKernelLabBackendId: "unlocked-browser-transformer",
        sharedRuntimeFallbackBackendId: "wasm-small-core",
        sharedRuntimeBackendRoleBoundaryPassed: true,
        sharedRuntimeMemoryProviderCount: 3,
        sharedRuntimeModelRegistryAligned: true,
        sharedRuntimeModelRegistryModelCount: 3,
        sharedRuntimePublicModelOptionCount: 2,
        sharedRuntimePublicDeployOptionCount: 1,
        sharedRuntimePublicKernelLabOptionCount: 1,
        sharedRuntimeContextTraceRequired: true,
        sharedRuntimeContextTraceBeforeGeneration: true,
        sharedRuntimeTracePersistedAfterGeneration: true,
        sharedRuntimeBackendProfilePassedToPlan: true,
      },
    })).toMatchObject({
      sharedRuntimeReadinessPassed: true,
      sharedRuntimeCoveredBackendCount: 3,
      sharedRuntimeDeployBackendId: "compiled-browser-webllm",
      sharedRuntimeKernelLabBackendId: "unlocked-browser-transformer",
      sharedRuntimeFallbackBackendId: "wasm-small-core",
      sharedRuntimeBackendRoleBoundaryPassed: true,
      sharedRuntimeMemoryProviderCount: 3,
      sharedRuntimeModelRegistryAligned: true,
      sharedRuntimeModelRegistryModelCount: 3,
      sharedRuntimePublicModelOptionCount: 2,
      sharedRuntimePublicDeployOptionCount: 1,
      sharedRuntimePublicKernelLabOptionCount: 1,
      sharedRuntimeContextTraceRequired: true,
      sharedRuntimeContextTraceBeforeGeneration: true,
      sharedRuntimeTracePersistedAfterGeneration: true,
      sharedRuntimeBackendProfilePassedToPlan: true,
    });
  });

  it("keeps backend readiness matrix fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        backendReadinessMatrixPassed: true,
        backendReadinessDeployBackendId: "compiled-browser-webllm",
        backendReadinessProductionCandidateCount: 1,
        backendReadinessDeployReadyCount: 1,
        backendReadinessResearchBackendCount: 1,
        backendReadinessKernelLabBackendId: "unlocked-browser-transformer",
        backendReadinessFallbackBackendCount: 1,
        backendReadinessFallbackBackendId: "wasm-small-core",
        backendReadinessFallbackDeployReadyCount: 0,
        backendReadinessRoleBoundaryPassed: true,
        backendReadinessModelRegistryAligned: true,
        backendReadinessModelRegistryModelCount: 3,
        backendReadinessPublicModelOptionCount: 2,
        backendReadinessPublicDeployOptionCount: 1,
        backendReadinessPublicKernelLabOptionCount: 1,
        backendReadinessCompiledHostedProfilePassed: true,
        backendReadinessCompiledDeployReady: true,
        backendReadinessProofBoundToHostedBenchmark: true,
        backendReadinessHostedBenchmarkProofSourceGitSha: "abc123",
        backendReadinessHostedBenchmarkExpectedSourceGitSha: "abc123",
        backendReadinessHostedBenchmarkProofSourceBound: true,
      },
    })).toMatchObject({
      backendReadinessMatrixPassed: true,
      backendReadinessDeployBackendId: "compiled-browser-webllm",
      backendReadinessProductionCandidateCount: 1,
      backendReadinessDeployReadyCount: 1,
      backendReadinessResearchBackendCount: 1,
      backendReadinessKernelLabBackendId: "unlocked-browser-transformer",
      backendReadinessFallbackBackendCount: 1,
      backendReadinessFallbackBackendId: "wasm-small-core",
      backendReadinessFallbackDeployReadyCount: 0,
      backendReadinessRoleBoundaryPassed: true,
      backendReadinessModelRegistryAligned: true,
      backendReadinessModelRegistryModelCount: 3,
      backendReadinessPublicModelOptionCount: 2,
      backendReadinessPublicDeployOptionCount: 1,
      backendReadinessPublicKernelLabOptionCount: 1,
      backendReadinessCompiledHostedProfilePassed: true,
      backendReadinessCompiledDeployReady: true,
      backendReadinessProofBoundToHostedBenchmark: true,
      backendReadinessHostedBenchmarkProofSourceGitSha: "abc123",
      backendReadinessHostedBenchmarkExpectedSourceGitSha: "abc123",
      backendReadinessHostedBenchmarkProofSourceBound: true,
    });
  });

  it("keeps hosted compiled deployment profile fields visible in release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        hostedProfilePassed: true,
        hostedProfileBackend: "compiled-browser-webllm",
        hostedProfileDefaultModel: "Qwen3-0.6B-q4f16_1-MLC",
        hostedProfileCompiledWebLlmEnabled: true,
        hostedProfileMtpProductionDisabled: true,
        hostedProfileTelemetryEnabled: true,
        hostedProfileTelemetryStorage: "postgres",
        hostedProfileTelemetryAdminProtected: true,
        hostedProfileTelemetryRateLimited: true,
        hostedProfileBenchmarkBackend: "compiled-browser-webllm",
        hostedProfileBenchmarkMemoryGrounding: "montana_capital",
        hostedProfileBenchmarkExpectedExact: "Helena",
        hostedProfileBenchmarkRequiresSubmitTelemetry: true,
      },
    })).toMatchObject({
      hostedProfilePassed: true,
      hostedProfileBackend: "compiled-browser-webllm",
      hostedProfileDefaultModel: "Qwen3-0.6B-q4f16_1-MLC",
      hostedProfileCompiledWebLlmEnabled: true,
      hostedProfileMtpProductionDisabled: true,
      hostedProfileTelemetryEnabled: true,
      hostedProfileTelemetryStorage: "postgres",
      hostedProfileTelemetryAdminProtected: true,
      hostedProfileTelemetryRateLimited: true,
      hostedProfileBenchmarkBackend: "compiled-browser-webllm",
      hostedProfileBenchmarkMemoryGrounding: "montana_capital",
      hostedProfileBenchmarkExpectedExact: "Helena",
      hostedProfileBenchmarkRequiresSubmitTelemetry: true,
    });
  });

  it("keeps unlocked WebGPU coverage visible in release gate latest summaries", () => {
    expect(summarizeReleaseGateArtifact({
      requestedBackendPreference: "webgpu",
      webGpuCoverage: {
        cpuFallbackUsed: true,
        mlpLayersByBackend: { webgpu: 0, cpu_reference: 1 },
        logitProjection: {
          backend: "cpu_reference",
          purpose: "full_vocab_topk_logit_projection",
          selectedRows: 64,
          fullRows: 151936,
        },
        decodeProjectionBackends: {
          oProjection: { webgpu: 0, cpu_reference: 1 },
        },
        attentionBackends: {
          prefill: { webgpu: 0, cpu_reference: 1 },
          decode: { webgpu: 0, cpu_reference: 1 },
          packedHeads: { webgpu: 0, cpu_reference: 2 },
          incompletePackedHeadProofs: 0,
        },
      },
      mtp: {
        mode: "draft_verify",
        verifierStrategy: "batched_continuation",
        verifiedTokenCount: 2,
        targetDecodeCalls: 1,
        acceptanceRate: 0.5,
      },
      kvPersistence: {
        decodeReuse: true,
        mode: "memory",
      },
    })).toMatchObject({
      requestedBackendPreference: "webgpu",
      cpuFallbackUsed: true,
      logitProjectionBackend: "cpu_reference",
      logitProjectionPurpose: "full_vocab_topk_logit_projection",
      logitProjectionSelectedRows: 64,
      logitProjectionFullRows: 151936,
      decodeOProjectionCpuReferenceLayers: 1,
      mtpMode: "draft_verify",
      mtpVerifierStrategy: "batched_continuation",
      mtpVerifiedTokenCount: 2,
      mtpTargetDecodeCalls: 1,
      kvDecodeReuse: true,
      kvPersistenceMode: "memory",
      mlpCpuReferenceLayers: 1,
      prefillAttentionCpuReferenceLayers: 1,
      decodeAttentionCpuReferenceLayers: 1,
      packedHeadCpuReference: 2,
      incompletePackedHeadProofs: 0,
    });
  });

  it("keeps Qwen parity accuracy thresholds visible in release gate latest summaries", () => {
    expect(summarizeReleaseGateArtifact({
      thresholds: {
        maxAbsError: 0.000001,
        deterministicTokenParity: true,
        retrievalGroundedResponse: true,
      },
      summary: {
        maxAbsError: 0,
        failedGateCount: 0,
        tokenParityPassed: true,
        multiTokenDecodePassed: true,
        retrievalGroundedPassed: true,
        realModelParityMode: "skipped",
      },
      suites: [
        { name: "rmsnorm", gates: [{ name: "max abs error", passed: true }] },
        {
          name: "real-model-parity",
          metrics: {
            modelId: "Qwen/Qwen3-0.6B",
            vocabSize: 151936,
            logitProjectionPurpose: "full_vocab_topk_logit_projection",
            logitProjectionSelectedRows: 8,
            logitProjectionFullRows: 151936,
          },
          gates: [{ name: "optional unless installed", passed: true }],
        },
      ],
    })).toMatchObject({
      maxAbsError: 0,
      maxAbsErrorThreshold: 0.000001,
      tokenParityPassed: true,
      multiTokenDecodePassed: true,
      retrievalGroundedPassed: true,
      realModelParityMode: "skipped",
      realModelId: "Qwen/Qwen3-0.6B",
      realModelVocabSize: 151936,
      realModelLogitProjectionPurpose: "full_vocab_topk_logit_projection",
      realModelLogitProjectionSelectedRows: 8,
      realModelLogitProjectionFullRows: 151936,
      gateCount: 2,
      failedGateCount: 0,
    });
  });

  it("uses completed browser-preview proof fields for strict runtime release summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        profile: "full",
        memoryMode: "browser-vector",
        promptCount: 1,
        meanInitLoadMs: 10,
        meanPrefillMs: 4,
        meanTimeToFirstTokenMs: 5,
        meanDecodeLatencyMs: 2,
        meanTokensPerSecond: 3,
        productionSpeedFloorPassed: true,
        browserPreviewMode: "completed",
        browserPreviewRequested: true,
        browserPreviewPassed: true,
        strictWebGpuPassed: false,
        cpuFallbackUsed: true,
      },
      browserPreview: {
        mode: "completed",
        requested: true,
        url: "http://127.0.0.1:5173/__bench/browser-runtime",
        passed: true,
        summary: {
          memoryQueryMode: "seeded_browser_vector_context_rebuild",
          memoryGroundingRequired: true,
          memoryGroundingPassed: true,
          memoryGroundingCoveragePassed: true,
          memoryExpectedHitPassed: true,
          memoryContextRebuildPassed: true,
          memoryAnswerOnlyPassed: true,
          memorySeededCorpusCount: 1024,
          memoryRetrievedCount: 7,
          memoryIncludedCount: 7,
          memoryRetrievalAuditRequired: true,
          memoryRetrievalAuditPassed: true,
          memoryRetrievalAuditQueryCount: 64,
          memoryRetrievalAuditTop1CorrectCount: 64,
          memoryRecallAt1: 1,
          memoryMrr: 1,
          memoryMinTopScoreMargin: 0.35,
          memoryMeanExpectedHitRank: 1,
          stopQualityPassed: true,
          stopQualityFailureCount: 0,
          runawayRepetitionPassed: true,
          runawayRepetitionFailureCount: 0,
          markerOnlyResponsePassed: true,
          markerOnlyResponseFailureCount: 0,
          generationStopReason: "stop_after_sequence",
          visibleResponseQualityPassed: true,
          expectedSubstringsPassed: true,
          expectedExactCheckCount: 1,
          expectedExactPassCount: 1,
          expectedExactPassed: true,
          technicalProofOnly: false,
          productionLayerCoverageRequired: true,
          productionLayerCoveragePassed: true,
          productionLayerVisitsPerToken: 28,
          productionMinLayerVisitsPerToken: 28,
          diagnosticCappedLayerRun: false,
          productionQualityPassed: true,
          productionDeployReadyPassed: true,
          groundedProductionReadyPassed: true,
          directModelFactualProofUsed: false,
          memoryGeneratedParaphraseRequired: true,
          memoryGeneratedParaphrasePassed: true,
          memoryGeneratedParaphraseQueryCount: 12,
          memoryGeneratedParaphraseTop1CorrectCount: 12,
          memoryGeneratedParaphraseRecallAt1: 1,
          memoryGeneratedParaphraseMrr: 1,
          primarySpeedBottleneck: "passed_speed_floor",
          decodeSubmitCount: 7,
          decodeSubmitCountPerToken: 7,
          v11CommandBatchingPassed: false,
          decodeDispatchCount: 9,
          decodeDispatchCountPerToken: 9,
          decodeDispatchCountPerLayerPerToken: 9,
          fusedLayerCoverage: 0,
          parityRecordCount: 0,
          parityPassedCount: 0,
          parityFailedCount: 0,
          strictWebGpuPassed: true,
          cpuFallbackUsed: false,
          requireKvReuse: true,
          kvReusePassed: true,
          kvExactReuseRunCount: 2,
          requireKvPredictivePrefetch: true,
          kvPredictivePrefetchPassed: true,
          kvPredictivePrefetchRunCount: 4,
          kvLowRankQuerySource: "persisted_q_rows",
          mtpMode: "target_only",
      },
      runs: [],
    },
  })).toMatchObject({
      browserBenchPreviewProductionDeployReadyPassed: true,
      browserBenchPreviewGroundedProductionReadyPassed: true,
      browserBenchPreviewMemoryGroundingPassed: true,
      browserBenchPreviewMemoryGeneratedParaphrasePassed: true,
      browserBenchMemoryGeneratedParaphraseRequired: true,
      browserBenchMemoryGeneratedParaphrasePassed: true,
      browserBenchMemoryGeneratedParaphraseQueryCount: 12,
      browserBenchMemoryGeneratedParaphraseTop1CorrectCount: 12,
      browserBenchMemoryGeneratedParaphraseRecallAt1: 1,
      browserBenchMemoryGeneratedParaphraseMrr: 1,
      browserBenchProductionSpeedFloorPassed: true,
      browserBenchMemoryQueryMode: "seeded_browser_vector_context_rebuild",
      browserBenchMemoryGroundingPassed: true,
      browserBenchMemorySeededCorpusCount: 1024,
      browserBenchMemoryRetrievalAuditPassed: true,
      browserBenchMemoryRetrievalAuditQueryCount: 64,
      browserBenchMemoryRetrievalAuditTop1CorrectCount: 64,
      browserBenchMemoryRecallAt1: 1,
      browserBenchMemoryMrr: 1,
      browserBenchMemoryMinTopScoreMargin: 0.35,
      browserBenchMemoryMeanExpectedHitRank: 1,
      browserBenchStopQualityPassed: true,
      browserBenchRunawayRepetitionPassed: true,
      browserBenchMarkerOnlyResponsePassed: true,
      browserBenchExpectedExactCheckCount: 1,
      browserBenchExpectedExactPassCount: 1,
      browserBenchExpectedExactPassed: true,
      browserBenchTechnicalProofOnly: false,
      browserBenchProductionLayerCoverageRequired: true,
      browserBenchProductionLayerCoveragePassed: true,
      browserBenchProductionLayerVisitsPerToken: 28,
      browserBenchProductionMinLayerVisitsPerToken: 28,
      browserBenchDiagnosticCappedLayerRun: false,
      browserBenchProductionQualityPassed: true,
      browserBenchProductionDeployReadyPassed: true,
      browserBenchGroundedProductionReadyPassed: true,
      browserBenchDirectModelFactualProofUsed: false,
      browserBenchPrimarySpeedBottleneck: "passed_speed_floor",
      browserBenchDecodeSubmitCount: 7,
      browserBenchDecodeSubmitCountPerToken: 7,
      browserBenchV11CommandBatchingPassed: false,
      browserBenchDecodeDispatchCount: 9,
      browserBenchDecodeDispatchCountPerToken: 9,
      browserBenchDecodeDispatchCountPerLayerPerToken: 9,
      browserBenchFusedLayerCoverage: 0,
      browserBenchParityRecordCount: 0,
      browserBenchParityPassedCount: 0,
      browserBenchParityFailedCount: 0,
      browserBenchStrictWebGpuPassed: true,
      cpuFallbackUsed: false,
      browserBenchRequireKvReuse: true,
      browserBenchKvReusePassed: true,
      browserBenchKvExactReuseRunCount: 2,
      browserBenchRequireKvPredictivePrefetch: true,
      browserBenchKvPredictivePrefetchPassed: true,
      browserBenchKvLowRankQuerySource: "persisted_q_rows",
      browserBenchMtpMode: "target_only",
    });
  });

  it("keeps browser runtime benchmark performance proof visible in release gate summaries", () => {
    expect(summarizeReleaseGateArtifact({
      summary: {
        profile: "ci",
        memoryMode: "browser-local-fixture",
        promptCount: 2,
        meanInitLoadMs: 12,
        meanPrefillMs: 7,
        meanTimeToFirstTokenMs: 9,
        meanDecodeLatencyMs: 4,
        meanTokensPerSecond: 250,
        generationTokenBudgetUsed: 16,
        browserPreviewMode: "skipped",
        browserPreviewRequested: false,
        browserPreviewPassed: false,
        browserPreviewRequired: true,
        memoryQueryMode: "seeded_browser_vector_context_rebuild",
        memoryGroundingPassed: true,
        memoryAnswerOnlyPassed: true,
        memorySeededCorpusCount: 64,
        memoryRetrievalAuditRequired: false,
        memoryRetrievalAuditPassed: true,
        memoryRecallAt1: 1,
        stopQualityPassed: true,
        stopQualityFailureCount: 0,
        runawayRepetitionPassed: true,
        runawayRepetitionFailureCount: 0,
        markerOnlyResponsePassed: true,
        markerOnlyResponseFailureCount: 0,
        expectedSubstringsPassed: true,
        productionSpeedFloorPassed: false,
        productionLayerCoverageRequired: true,
        productionLayerCoveragePassed: false,
        productionLayerVisitsPerToken: 8,
        productionMinLayerVisitsPerToken: 28,
        diagnosticCappedLayerRun: true,
        primarySpeedBottleneck: "unfused_decode_layer_path",
        decodeSubmitCount: 40,
        decodeSubmitCountPerToken: 20,
        v11CommandBatchingPassed: true,
        decodeDispatchCount: 60,
        decodeDispatchCountPerToken: 30,
        decodeDispatchCountPerLayerPerToken: 1.071,
        fusedLayerCoverage: 0,
        parityRecordCount: 0,
        parityPassedCount: 0,
        parityFailedCount: 0,
        requireKvReuse: true,
        kvReusePassed: true,
        requireKvPredictivePrefetch: true,
        kvPredictivePrefetchPassed: true,
        kvLowRankQuerySource: "persisted_q_rows",
        mtpMode: "draft_verify",
        mtpAcceptanceRate: 0.5,
        strictWebGpuRequired: true,
        strictWebGpuPassed: false,
        strictWebGpuGateCount: 4,
        strictWebGpuFailureCount: 2,
        blockingThresholdFailures: 0,
      },
      webGpuCoverage: {
        cpuFallbackUsed: true,
        logitProjection: { backend: "cpu_reference" },
        mlpLayersByBackend: { cpu_reference: 1 },
      },
    })).toMatchObject({
      browserBenchProfile: "ci",
      browserBenchMemoryMode: "browser-local-fixture",
      browserBenchPromptCount: 2,
      browserBenchMeanInitLoadMs: 12,
      browserBenchMeanPrefillMs: 7,
      browserBenchMeanTtftMs: 9,
      browserBenchMeanDecodeLatencyMs: 4,
      browserBenchMeanTokensPerSecond: 250,
      browserBenchGenerationTokenBudgetUsed: 16,
      browserBenchPreviewMode: "skipped",
      browserBenchPreviewRequested: false,
      browserBenchPreviewPassed: false,
      browserBenchPreviewRequired: true,
      browserBenchMemoryQueryMode: "seeded_browser_vector_context_rebuild",
      browserBenchMemoryGroundingPassed: true,
      browserBenchMemoryAnswerOnlyPassed: true,
      browserBenchMemorySeededCorpusCount: 64,
      browserBenchMemoryRetrievalAuditRequired: false,
      browserBenchMemoryRetrievalAuditPassed: true,
      browserBenchMemoryRecallAt1: 1,
      browserBenchStopQualityPassed: true,
      browserBenchStopQualityFailureCount: 0,
      browserBenchRunawayRepetitionPassed: true,
      browserBenchRunawayRepetitionFailureCount: 0,
      browserBenchMarkerOnlyResponsePassed: true,
      browserBenchMarkerOnlyResponseFailureCount: 0,
      browserBenchExpectedSubstringsPassed: true,
      browserBenchProductionSpeedFloorPassed: false,
      browserBenchProductionLayerCoverageRequired: true,
      browserBenchProductionLayerCoveragePassed: false,
      browserBenchProductionLayerVisitsPerToken: 8,
      browserBenchProductionMinLayerVisitsPerToken: 28,
      browserBenchDiagnosticCappedLayerRun: true,
      browserBenchPrimarySpeedBottleneck: "unfused_decode_layer_path",
      browserBenchDecodeSubmitCount: 40,
      browserBenchDecodeSubmitCountPerToken: 20,
      browserBenchV11CommandBatchingPassed: true,
      browserBenchDecodeDispatchCount: 60,
      browserBenchDecodeDispatchCountPerToken: 30,
      browserBenchDecodeDispatchCountPerLayerPerToken: 1.071,
      browserBenchFusedLayerCoverage: 0,
      browserBenchParityRecordCount: 0,
      browserBenchParityPassedCount: 0,
      browserBenchParityFailedCount: 0,
      browserBenchRequireKvReuse: true,
      browserBenchKvReusePassed: true,
      browserBenchRequireKvPredictivePrefetch: true,
      browserBenchKvPredictivePrefetchPassed: true,
      browserBenchKvLowRankQuerySource: "persisted_q_rows",
      browserBenchMtpMode: "draft_verify",
      browserBenchMtpAcceptanceRate: 0.5,
      browserBenchStrictWebGpuRequired: true,
      browserBenchStrictWebGpuPassed: false,
      browserBenchStrictWebGpuGateCount: 4,
      browserBenchStrictWebGpuFailureCount: 2,
      browserBenchBlockingThresholdFailures: 0,
      cpuFallbackUsed: true,
    });
  });

  it("keeps completed browser preview proof visible even when nested on the benchmark artifact", () => {
    expect(summarizeReleaseGateArtifact({
      browserPreview: {
        mode: "completed",
        requested: true,
        passed: true,
      },
    })).toMatchObject({
      browserBenchPreviewMode: "completed",
      browserBenchPreviewRequested: true,
      browserBenchPreviewPassed: true,
    });
  });

  it("keeps packed tensor storage proof visible in release gate summaries", () => {
    expect(summarizeReleaseGateArtifact({
      tensorStorage: {
        explicit: true,
        format: "f16-packed",
        dtype: "f16",
        shardKind: "f16-shard",
        byteWidth: 2,
        productionTarget: "webgpu-packed",
        runtimeRepresentation: "packed-f16-runtime-lazy-decode",
        packedRuntimeCompute: false,
        packedProductionReady: true,
      },
    })).toMatchObject({
      tensorStorageExplicit: true,
      tensorStorageFormat: "f16-packed",
      tensorStorageDtype: "f16",
      tensorStorageShardKind: "f16-shard",
      tensorStorageByteWidth: 2,
      tensorStorageProductionTarget: "webgpu-packed",
      tensorStorageRuntimeRepresentation: "packed-f16-runtime-lazy-decode",
      packedRuntimeCompute: false,
      packedProductionReady: true,
    });
  });

  it("keeps requested SDK deployment preset smoke proof visible in release gate summaries", () => {
    expect(summarizeReleaseGateArtifact({
      metrics: {
        mountedIframeCount: 1,
        requestedDeploymentPreset: "remote-http",
        requestedSdkMode: "launcher",
        requestedMemoryMode: "remote-http",
        requestedSidecarDisabled: true,
        noSecretQueryParams: true,
      },
      gates: [
        { name: "requested deployment preset routed", passed: true },
        { name: "requested launcher mode routed", passed: true },
        { name: "no secret query params", passed: true },
      ],
    })).toMatchObject({
      mountedIframeCount: 1,
      sdkRequestedDeploymentPreset: "remote-http",
      sdkRequestedMode: "launcher",
      sdkRequestedMemoryMode: "remote-http",
      sdkRequestedSidecarDisabled: true,
      sdkNoSecretQueryParams: true,
      gateCount: 3,
      failedGateCount: 0,
    });
    expect(summarizeReleaseGateArtifact({
      metrics: {
        requestedMemoryMode: "remote-http",
      },
    })).not.toHaveProperty("sdkMemoryMode");
  });
});
